# Generated by Django 6.0.2 on 2026-03-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0006_tag_blogpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Desmárquelo para ocultar este proyecto de la página web sin eliminarlo.', verbose_name='Publicado'),
        ),
    ]
