name: Sync to Client Repository

on:
  push:
    branches:
      - main # O la rama que uses como principal

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Client Repo
        run: |
          git remote add client https://${{ secrets.MARCELO_GITHUB_TOKEN }}@github.com/mcampbelldev/MC-portfolio.git
          git push client main:main --force
